###
POST http://localhost:8000/api/payments
Content-Type: application/json

{

   "user_id":1,
   "session_id":1,
   "amount": 5000,
   "payment_status":"paid",
   "payment_date": "2025-02-05",
   "stripe_payment_id": "1"
}
###
PUT http://localhost:8000/api/payments/1
Content-Type: application/json

{

     "payment_status":"not-paid"
}
###
POST http://localhost:8000/api/payments/create-payment-intent
Content-Type: application/json

{
  "userId": 1,
  "sessionId": 1,
  "amount": 17050,     
  "currency": "usd",
  "paymentStatus": "complete"
}

###
DELETE http://localhost:8000/api/payments/2


####
//get all payments
GET http://localhost:8000/api/payments
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsiZnVsbF9uYW1lIjoiQ2hyaXN0aW5lIFJpYW4gIiwiY29udGFjdF9waG9uZSI6IjA3OTkwODcxODgiLCJhZGRyZXNzIjoiOTAga2VueWEiLCJpZCI6MX0sInJvbGUiOiJhZG1pbiIsImV4cCI6MTczOTM4MzMyNn0.xfTWm_UF329TEzqZiLqtjGk01B9tXIUZWT5-KWVeqI4